CUDA_VISIBLE_DEVICES=0 ns-train  umhsnerf \
 --machine.seed 42 \
 --log-gradients True \
 --pipeline.num_classes 7 \
 --pipeline.model.far-plane 1000 \
 --pipeline.model.near_plane 0.05 \
 --pipeline.model.background-color random \
 --pipeline.datamanager.images-on-gpu True \
 --pipeline.datamanager.patch-size 1 \
 --pipeline.datamanager.train-num-rays-per-batch 8192 \
 --pipeline.model.method rgb+spectral \
 --pipeline.model.implementation tcnn \
 --data data/processed/ajar  \
 --experiment-name "temperature 0.2" \
 --vis wandb --viewer.websocket-port 7009 \